/*
 * Copyright (C) 2017 mayurdivate
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package umac.guava.diff;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import umac.guava.Genome;

/**
 *
 * @author mayurdivate
 */
public class DifferentialInputFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form DifferentialInputParameters
     */
    
    
    public DifferentialInputFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMethod = new javax.swing.JLabel();
        jLabelFC = new javax.swing.JLabel();
        jLabelPvalue = new javax.swing.JLabel();
        jLabelDownStream = new javax.swing.JLabel();
        jLabelGenome = new javax.swing.JLabel();
        jComboBoxFC = new javax.swing.JComboBox<>();
        jComboBoxMetho = new javax.swing.JComboBox<>();
        jTextFieldDownstream = new javax.swing.JTextField();
        jTextFieldPvalue = new javax.swing.JTextField();
        jLabelUpStream = new javax.swing.JLabel();
        jTextFieldUpstream = new javax.swing.JTextField();
        jLabelCPU = new javax.swing.JLabel();
        jSpinnerCPUs = new javax.swing.JSpinner();
        jComboBoxGenome = new javax.swing.JComboBox<>();
        jButtonOutputFolder = new javax.swing.JButton();
        jTextFieldOutputFolder = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelBackResetNextButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Differential Analysis Parameters", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));

        jLabelMethod.setText("Analysis Method ");

        jLabelFC.setText("log2 ( Fold Change )");

        jLabelPvalue.setText("P value");

        jLabelDownStream.setText("Downstream of TSS");

        jLabelGenome.setText("Genome");

        jComboBoxFC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2","1.5","1"}));

        jComboBoxMetho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DESeq2" }));

        jTextFieldDownstream.setText("3000");
        jTextFieldDownstream.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDownstreamKeyTyped(evt);
            }
        });

        jTextFieldPvalue.setText("0.05");
        jTextFieldPvalue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPvalueKeyTyped(evt);
            }
        });

        jLabelUpStream.setText("Upstream of TSS");

        jTextFieldUpstream.setText("5000");
        jTextFieldUpstream.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUpstreamKeyTyped(evt);
            }
        });

        jLabelCPU.setText("CPUs");

        jSpinnerCPUs.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        String[] genomes = Genome.getGenomeArray();
        jComboBoxGenome.setMaximumRowCount(5);
        jComboBoxGenome.setModel(new javax.swing.DefaultComboBoxModel<>(genomes));
        jComboBoxGenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenomeActionPerformed(evt);
            }
        });

        jButtonOutputFolder.setText("output folder");
        jButtonOutputFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputFolderActionPerformed(evt);
            }
        });

        jTextFieldOutputFolder.setEditable(false);
        jTextFieldOutputFolder.setDragEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelMethod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabelUpStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMetho, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUpstream))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDownStream, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDownstream, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelPvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelGenome, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPvalue, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGenome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jLabelCPU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerCPUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldOutputFolder)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMetho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPU)
                    .addComponent(jSpinnerCPUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDownStream, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDownstream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpStream, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUpstream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Please fill the following parmeters ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5))
        );

        jPanelBackResetNextButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Andale Mono", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Andale Mono", 0, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonStart.setFont(new java.awt.Font("Andale Mono", 0, 14)); // NOI18N
        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackResetNextButtonsLayout = new javax.swing.GroupLayout(jPanelBackResetNextButtons);
        jPanelBackResetNextButtons.setLayout(jPanelBackResetNextButtonsLayout);
        jPanelBackResetNextButtonsLayout.setHorizontalGroup(
            jPanelBackResetNextButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackResetNextButtonsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanelBackResetNextButtonsLayout.setVerticalGroup(
            jPanelBackResetNextButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackResetNextButtonsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBackResetNextButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Tools");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBackResetNextButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelBackResetNextButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        
        if(validateInputs()){
            
            File outputFolder =  new File(jTextFieldOutputFolder.getText());
            DifferentialResultFrame.outputFolder = outputFolder;
            Genome genome = Genome.getGenomeObject(jComboBoxGenome.getSelectedItem().toString());
            DifferentialResultFrame.genome = genome;
            
            DifferentialOutputFiles dof = DifferentialOutputFiles.getDifferentialOutputFiles(outputFolder,genome);
        
            double foldchange =  Double.parseDouble(jComboBoxFC.getSelectedItem().toString());
            double pvalue =  Double.parseDouble(jTextFieldPvalue.getText());
            int downstream = Integer.parseInt(jTextFieldDownstream.getText());
            int upstream = Integer.parseInt(jTextFieldUpstream.getText());
            
            String method = jComboBoxMetho.getSelectedItem().toString();
            int cpus = (int) jSpinnerCPUs.getValue();
            
            GdiffInput gdiffInput = new GdiffInput(outputFolder, dof, foldchange, pvalue, 
                    DifferentialInputFrame1.dfInputList, DifferentialInputFrame1.projectName, 
                    genome, upstream, downstream,method, cpus );
            this.dispose();
            
            new DifferentialAnalysisWorkflow().startDifferentialAnalysis(gdiffInput);
        }
    }//GEN-LAST:event_jButtonStartActionPerformed
    
    private boolean validateInputs(){
        
        boolean flag = true;
        
        File outputFolder = new File(jTextFieldOutputFolder.getText());
        double pvalue =  Double.parseDouble(jTextFieldPvalue.getText());
        int downstream = Integer.parseInt(jTextFieldDownstream.getText());
        int upstream = Integer.parseInt(jTextFieldUpstream.getText());
        
        if(!outputFolder.exists()){
            flag = false;
            jButtonOutputFolder.setForeground(Color.red);
            jTextFieldOutputFolder.setForeground(Color.red);
        }
        
        if(pvalue < 0 || pvalue > 0.05) {
            flag = false;
            jTextFieldPvalue.setForeground(Color.red);
        }
        
        if(downstream < 0) {
            flag = false;
            jTextFieldDownstream.setForeground(Color.red);
        }
        
        if(upstream < 0) {
            flag = false;
            jTextFieldUpstream.setForeground(Color.red);
        }
        
        if(jComboBoxGenome.getSelectedIndex() == 0){
            flag = false;
            jLabelGenome.setForeground(Color.red);
        }
        return flag;
    
    }
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        DifferentialInputFrame1.differentialInputFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jComboBoxMetho.setSelectedIndex(0);
        jComboBoxFC.setSelectedIndex(0);
        jComboBoxGenome.setSelectedIndex(0);
        jTextFieldDownstream.setText("3000");
        jTextFieldUpstream.setText("5000");
        jTextFieldPvalue.setText("0.05");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonOutputFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputFolderActionPerformed
        // TODO add your handling code here:
        JFileChooser addFileChooser = new JFileChooser();
        addFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(DifferentialInputFrame1.lastPath != null){
            addFileChooser.setCurrentDirectory(DifferentialInputFrame1.lastPath);
        }

        addFileChooser.setDialogTitle("Select output folder");
        
        int returnVal = addFileChooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File outputDir = addFileChooser.getSelectedFile();
            jTextFieldOutputFolder.setText(outputDir.getAbsolutePath());
            DifferentialOutputFiles.setOutFolder(outputDir);
            jTextFieldOutputFolder.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jButtonOutputFolderActionPerformed

    private void jTextFieldDownstreamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDownstreamKeyTyped
        // TODO add your handling code here:
        jTextFieldDownstream.setForeground(Color.black);
        char key =  evt.getKeyChar();
        if(!Character.isDigit(key)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDownstreamKeyTyped

    private void jTextFieldUpstreamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUpstreamKeyTyped
        // TODO add your handling code here:
        jTextFieldUpstream.setForeground(Color.black);
        char key =  evt.getKeyChar();
        if(!Character.isDigit(key)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldUpstreamKeyTyped

    private void jTextFieldPvalueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPvalueKeyTyped
        // TODO add your handling code here:
        jTextFieldPvalue.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldPvalueKeyTyped

    private void jComboBoxGenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenomeActionPerformed
        // TODO add your handling code here:
        if(jComboBoxGenome.getSelectedIndex() > 0){
            jLabelGenome.setForeground(Color.black);
        }
    }//GEN-LAST:event_jComboBoxGenomeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOutputFolder;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JComboBox<String> jComboBoxFC;
    private javax.swing.JComboBox<String> jComboBoxGenome;
    private javax.swing.JComboBox<String> jComboBoxMetho;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCPU;
    private javax.swing.JLabel jLabelDownStream;
    private javax.swing.JLabel jLabelFC;
    private javax.swing.JLabel jLabelGenome;
    private javax.swing.JLabel jLabelMethod;
    private javax.swing.JLabel jLabelPvalue;
    private javax.swing.JLabel jLabelUpStream;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBackResetNextButtons;
    private javax.swing.JSpinner jSpinnerCPUs;
    private javax.swing.JTextField jTextFieldDownstream;
    private javax.swing.JTextField jTextFieldOutputFolder;
    private javax.swing.JTextField jTextFieldPvalue;
    private javax.swing.JTextField jTextFieldUpstream;
    // End of variables declaration//GEN-END:variables
}
